### PR TITLE
Change detailed type analysis to use `ErrorHandler`

### LINKED ISSUE #60: Use `ErrorHandler` in detailed name/type analysis
It would improve the detailed name and type analysis, if we were able to report more than one error. The necessary changes include moving from exception throwing to collecting errors (easy), as well as taking into account that reporting an error would not end the method immediately, potentialy causing follow-up errors (more complicated).

### PR DESCRIPTION
**Pull request by larsk21**
closes #60 

fixed bugs:
- for a default binary expression with an incompatible type on the right side of the operator, the error message included the type of the expression on the left side
- if a method invocation had too many arguments, the nodes of the additional arguments were not visited

### CODE REVIEW

**Comment by larsk21** [comment]
Example with multiple errors:
```
class Test {
    public static void main(String[] args) {
        Test test = new Test();
        int x = test.f(5, true, test.g(17));
    }
    public boolean f(int x, int y) {
        return x == y;
    }
}
```

Output:
```
error: semantic check at line 4, column 22: wrong number of arguments
error: semantic check at line 4, column 22: argument 1 of type boolean does not match expected type int
error: semantic check at line 4, column 38: unknown method
error: semantic check at line 4, column 9: invalid assigment, variable type is int while expression type is boolean
```

File: src/main/java/edu/kit/compiler/semantic/DetailedNameTypeAstVisitor.java [hunk 1]
```diff
@@ -125,210 +127,252 @@ public DataType visit(ClassNode classNode) {
...
-        return VoidType;
+        return Optional.empty();
     }
 
-    public DataType visit(BinaryExpressionNode binaryExpressionNode) {
-        DataType leftSideType = binaryExpressionNode.getLeftSide().accept(this);
-        DataType rightSideType = binaryExpressionNode.getRightSide().accept(this);
+    private Optional<DataType> applyResultType(ExpressionNode expressionNode, Optional<DataType> resultType_) {
+        resultType_.ifPresentOrElse(resultType -> {
+            expressionNode.setResultType(resultType);
```
Comment (g4rgoil) [inline src/main/java/edu/kit/compiler/semantic/DetailedNameTypeAstVisitor.java:285]: Some of your lambdas could be simplified using method references (in this case `expressionNode::setResultType`).

File: src/main/java/edu/kit/compiler/semantic/DetailedNameTypeAstVisitor.java [hunk 2]
```diff
@@ -125,210 +127,252 @@ public DataType visit(ClassNode classNode) {
...
 
-                resultType = leftSideType;
+                resultType_ = leftSideType_;
                 break;
             case Equal:
             case NotEqual:
-                if (!leftSideType.isCompatibleTo(rightSideType)) {
-                    semanticError(binaryExpressionNode, "the two arguments of %s must have compatible types", operator);
-                }
+                leftSideType_.ifPresent(leftSideType -> rightSideType_.ifPresent(rightSideType -> {
```
Comment (g4rgoil) [inline src/main/java/edu/kit/compiler/semantic/DetailedNameTypeAstVisitor.java:319]: You use this double `ifPresent` construct quite a few times, you could consider a helper method for this to make it more readable (something like `ifBoth(Optional<S>, Optional<T>, BiFunction<S, T, R>)`).

File: src/main/java/edu/kit/compiler/semantic/DetailedNameTypeAstVisitor.java (hunk 1 above)
Comment (larsk21) [reply src/main/java/edu/kit/compiler/semantic/DetailedNameTypeAstVisitor.java:285]: I'm aware and I, personally, like them better, I just made the experience that some developers find them hard to read.

File: src/main/java/edu/kit/compiler/semantic/DetailedNameTypeAstVisitor.java (hunk 2 above)
Comment (larsk21) [reply src/main/java/edu/kit/compiler/semantic/DetailedNameTypeAstVisitor.java:319]: I'm unsure if it would be more readable, but I can change it if it helps.

**Review by g4rgoil — APPROVED** [review]
Looks good
